title: Anthony A. Nader | Software Developer
description: Recent business graduate pursuing a software engineering degree at the University of Ottawa. Full-time learner and technology enthusiast passionate about music software development, web, and native iOS applications.
author: Anthony A. Nader
email: hello@anthonyanader.com
permalink: pretty
baseurl: ""
url: "http://anthonyanader.com"
default_bg: default_bg.png
twitter: https://twitter.com/anthony_aanader
github: https://github.com/anthonyanader
linkedin: https://www.linkedin.com/in/anthonyanader
include: [_pages]
exclude: ['README.md']
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
