title: Anthony A. Nader | Software Developer
description: Recent business graduate pursuing a software engineering degree at the University of Ottawa.
author: Anthony A. Nader
email: hello@anthonyanader.com
permalink: pretty
baseurl: ""
url: "https://anthonyanader.com"
default_bg: default_bg.png
future: true

twitter: https://twitter.com/anthony_aanader
github: https://github.com/anthonyanader
linkedin: https://www.linkedin.com/in/anthonyanader
spotify: https://open.spotify.com/user/djconceptt
soundcloud: https://soundcloud.com/djconceptt
goodreads: https://www.goodreads.com/user/show/41290787-anthony-a-nader

include: [_pages]
exclude: ['README.md']
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
