title: Anthony A. Nader | Software Developer
email: hello@anthonyanader.com
permalink: none
baseurl: "/personalBlog"
url: ""

# Contact links
email: hello@anthonyanader.com
website: anthonyanader.com
linkedin: anthonyanader
github: anthonyanader
twitter: '@anthony_aanader'
devpost: anthonyanader
codepen: anthonyanader

include: [_pages]
exclude: ['README.md']
