title: Anthony A. Nader | Software Developer
description: Recent business graduate pursuing a software engineering degree at the University of Ottawa. Full-time learner and technology enthusiast passionate about music software development, web, and native iOS applications.
author: Anthony A. Nader
email: hello@anthonyanader.com
permalink: none
baseurl: ""
url: "anthonyanader.github.io"
twitter:
  username: anthony_aanader
socials:
    name: Anthony A. Nader
    links:
        - https://twitter.com/anthony_aanader
        - https://www.linkedin.com/in/anthonyanader/
        - https://github.com/anthonyanader
include: [_pages]
exclude: ['README.md']
plugins:
  - jekyll-seo-tag
  - jekyll-mentions
  - jemoji
